-------------------------------------------------------------------------------
Test set: TestSuite
-------------------------------------------------------------------------------
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 41.912 s <<< FAILURE! - in TestSuite
DataProviderTest.myTest[5, 7, 2](2)  Time elapsed: 0.163 s  <<< FAILURE!
java.lang.AssertionError: expected [12] but found [2]
	at DataProviderTest.myTest(DataProviderTest.java:16)

